pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                bat '''
                    cd RESTAURANT-BILLING-SYSTEM_
                    docker build -t restaurant-billing:latest .
                '''
            }
        }

        stage('Deploy MySQL') {
            steps {
                bat '''
                    cd RESTAURANT-BILLING-SYSTEM_
                    docker compose up -d mysql
                '''
            }
        }

        stage('Verify Docker') {
            steps {
                bat '''
                    cd RESTAURANT-BILLING-SYSTEM_
                    docker ps
                    docker volume ls
                '''
            }
        }
    }

    post {
        success {
            echo 'Restaurant Billing System Docker deployment completed!'
        }

        failure {
            echo 'Docker deployment failed. Check the Jenkins console output.'
        }
    }
}